In [1]:
# EJEMPLOS CON LA LIBRERÍA NUMPY

In [2]:
import numpy as np

# qué versión tengo?
np.version.version 

'1.20.2'

In [3]:
# Crear un array vacío
a = np.array([])
print(a) 

[]


In [4]:
# crear un array
a1D = np.array([1, 2, 3, 4, 5])

print('El arreglo unidimensional que cree tiene:',a1D)

El arreglo unidimensional que cree tiene: [1 2 3 4 5]


In [5]:
# de qué tipo es?
type(a1D)

numpy.ndarray

In [6]:
# existe el array Numpy llamado a1D:
if isinstance(a1D, np.ndarray):
    print('Existe')
    print(a1D)
else:
    print('No existe') 


Existe
[1 2 3 4 5]


In [7]:
# Crear un nuevo array bidimensional (2x3) para datos de tipo float
a2D = np.array([[1, 2, 3], [4, 5.8, 6]], dtype=float)
print(a2D) 

[[1.  2.  3. ]
 [4.  5.8 6. ]]


In [8]:
# Crear un array tridimensional (2x2x2) para datos de tipo int:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=int)
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Crear un array de (3x3) con números aleatorios
aa = np.random.random((3,3))
print(aa)

[[0.91019235 0.70063955 0.88508693]
 [0.98195832 0.86455291 0.28643635]
 [0.76975182 0.04134251 0.8780905 ]]


In [10]:
# Crear un array (3x3) con la matriz identidad. Esta matriz matriz 
#es una matriz cuadrada donde todos sus elementos son ceros (0) 
#excepto los elementos de la diagonal principal que son unos (1).

ai = np.identity(3)
print(ai)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Crear un array con los elementos de una tupla

tupla = (1, 2, 3, 4, 5)
at = np.asarray(tupla)
print(at) 

[1 2 3 4 5]


In [12]:
# Crear un array (2x3) con los elementos de una lista

lista = [[1, 2, 3], [4, 5, 6]]
print('La lista es:', lista)
al = np.asarray(lista)
print('El arreglo es: \n',al)

La lista es: [[1, 2, 3], [4, 5, 6]]
El arreglo es: 
 [[1 2 3]
 [4 5 6]]


In [13]:
# Generar datos aleatorios de una matriz de 2x3
data = np.random.randn(2,3)
data

array([[ 0.39320746, -0.81364857, -1.13590601],
       [ 1.15113394, -0.83602999, -0.39264064]])

In [14]:
#luego escribimos funciones aritméticas con los datos :
data * 10

array([[  3.93207455,  -8.13648573, -11.35906006],
       [ 11.51133941,  -8.36029988,  -3.92640639]])

In [15]:
data + data

array([[ 0.78641491, -1.62729715, -2.27181201],
       [ 2.30226788, -1.67205998, -0.78528128]])

In [16]:
#una matriz solo puede ser de un tipo
data.dtype

dtype('float64')

In [17]:
#cómo es la matriz?
data.shape

(2, 3)

In [18]:
# ejemplo de slicing

# Crear una matriz de 3x4

a3x4 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a3x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# Usar slicing para extraer una submatriz que posea las 2 primeras filas de las columnas 1 y 2; 
# entonces b es una matriz de forma 2x2
b = a3x4[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [20]:
# diferentes operaciones: 
#la primera fila,columna es 0,0
print(a3x4[0, 0]) #imprime 1

1


In [21]:
print(a3x4[0, 1])   # imprime 2

2


In [22]:
b[0, 0] = 77     # b[0, 0] es lo mismo que a[0, 1]
print(a3x4[0, 1])   # imprime "77"

77


In [23]:
# Los arreglos deben ser del mismo tipo, y los va a crear de esa forma..
#por ejemplo si queremos crear esta matriz va a crearla toda como string, ya que hay un número que es string
a4x3 = np.array([[1,2,3], [4,5,6], [7,8,'asa'], [10, 11, 12]])
print(a4x3)  
print('El tipo de la matriz es: ', a4x3.dtype)
print()

#si ahora hacemos:
a4x3 = np.array([[1,2,3], [4,5,6], [7,8,3.14], [10, 11, 12]])
print(a4x3)  
print('El tipo de la matriz es: ', a4x3.dtype)
print()

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' 'asa']
 ['10' '11' '12']]
El tipo de la matriz es:  <U21

[[ 1.    2.    3.  ]
 [ 4.    5.    6.  ]
 [ 7.    8.    3.14]
 [10.   11.   12.  ]]
El tipo de la matriz es:  float64



In [24]:
#otro ejemplo
nombre = np.array(['Juan', 'Sol', 'Lucia', 'Juan', 'Lucia', 'Sol', 'Sol'])
nombre

array(['Juan', 'Sol', 'Lucia', 'Juan', 'Lucia', 'Sol', 'Sol'], dtype='<U5')

In [25]:
#analiza la condición por cada elemento
nombre == 'Juan'

array([ True, False, False,  True, False, False, False])

In [26]:
print(nombre)
mask = (nombre == 'Juan') | (nombre == 'Lucia')
mask

['Juan' 'Sol' 'Lucia' 'Juan' 'Lucia' 'Sol' 'Sol']


array([ True, False,  True,  True,  True, False, False])

In [27]:
nombre[nombre < 'Lum'] = 0
print(nombre)

['0' 'Sol' '0' '0' '0' 'Sol' 'Sol']


In [28]:
nombre[nombre == '0'] =  'Juan'
print(nombre)

['Juan' 'Sol' 'Juan' 'Juan' 'Juan' 'Sol' 'Sol']


In [29]:
#operaciones sobre matrices
a4x3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a4x3) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
#calcular la raíz cuadrada
np.sqrt(a4x3)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [31]:
# elevarlo al cuadrado
aa = np.square(a4x3)
aa

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [32]:
# volvemos a ko que teniamos pero ahora de tipo float
aa = np.sqrt(aa)
aa

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [33]:
#calcular la media
np.mean(aa)

6.5

In [34]:
np.median(aa)

6.5